[package]
name = "spark_cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "spark"
path = "src/main.rs"

[dependencies]
clap = "4.5.4"
